lab4/urls.py
from django.urls import path
from .views import index, add_note, note_list

app_name = "lab4"
urlpatterns = [
    path('', index, name='index'),
    path('add-note', add_note, name='formNote'),
    path('note-list', note_list, name='noteCard'),
]

lab_1/urls.py
from django.urls import path
from .views import index, friend_list

urlpatterns = [
    path('', index, name='index'),
    path('friends', friend_list, name='friend list'),
]

lab_2/urls.py
from django.urls import path
from .views import index, xml, json

urlpatterns = [
    path('', index, name='index'),
    path('xml', xml, name='xml_format'),
    path('json', json, name='JSON_format'),
]

lab_3/urls.py
from django.urls import path
from .views import add_friend, index

urlpatterns = [
    path('', index, name='index'),
    path('add', add_friend, name="addFriend")
]

praktikum/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab4.urls as lab_4
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include('lab_1.urls')),
    path('lab-2/', include('lab_2.urls')),
    path('lab-3/', include('lab_3.urls')),
    path('lab-4/', include('lab4.urls')),
    re_path(r'^$', index_lab1, name='index')
]

lab4/models.py
from django.db import models

# Create your models here.

lab_1/models.py
from django.db import models


class Friend(models.Model):
    name = models.CharField(max_length=30)
    npm = models.CharField(max_length=10)
    dob = models.DateField()

lab_2/models.py
from django.db import models

# Create your models here.


class Note(models.Model):
    to = models.CharField(max_length=100)
    froms = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    message = models.TextField()

lab_3/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

# Create your models here.

lab4/forms.py
from lab_2.models import Note
from django import forms


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = '__all__'
        # kalo pake all ini ga bisa pake error messages & input_attrs & display name
        # kalo pake ini ['display_name'], fieldsnya bakal dihandle di HTML forms

lab_3/forms.py
from lab_1.models import Friend
from django import forms


class DateInput(forms.DateInput):
    input_type = 'date'


class FriendForm(forms.ModelForm):
    class Meta:
        widgets = {'dob': DateInput()}
        model = Friend
        fields = '__all__'
        # kalo pake all ini ga bisa pake error messages & input_attrs & display name
        # kalo pake ini ['display_name'], fieldsnya bakal dihandle di HTML forms

lab4/views.py
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from lab4.forms import NoteForm
from lab_2.models import Note

# Create your views here.


def index(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab4_index.html', response)


def add_note(request):
    context = {}

    form = NoteForm(request.POST or None)

    if form.is_valid() and request.method == 'POST':
        form.save()
        return HttpResponseRedirect("/lab-4")
    context['form'] = form
    return render(request, "lab4_form.html", context)


@login_required(login_url="/admin/login/")
def note_list(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab4_note_list.html', response)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = 'Yelda Faizah Havara'
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2003, 1, 10)
npm = 2006464386


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all()
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.http.response import HttpResponse
from django.core import serializers
from .models import Note
from django.shortcuts import render

# Create your views here.


def index(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab2.html', response)

# views tu selalu nerima argumen, walaupun ga dipake dimana" di dlm function ini dia tetep harus ada parameternya


def xml(request):
    notes = Note.objects.all()
    data = serializers.serialize('xml', notes)
    return HttpResponse(data, content_type="application/xml")


def json(request):
    notes = Note.objects.all()
    data = serializers.serialize('json', notes)
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from lab_1.models import Friend
from .forms import FriendForm
from django.contrib.auth.decorators import login_required


@login_required(login_url="/admin/login/")
def index(request):
    friends = Friend.objects.all()
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)


# kalo mau ngeadd friend harus login dulu
@login_required(login_url="/admin/login/")
def add_friend(request):
    context = {}

    form = FriendForm(request.POST or None)

    if form.is_valid() and request.method == 'POST':
        form.save()
        return HttpResponseRedirect("/lab-3")
    context['form'] = form
    return render(request, "lab3_form.html", context)


# kalo misal udah ngisi data trus submit langsung redirect ke halaman index lab3

lab_5/views.py
from django.shortcuts import render

# Create your views here.

lab4/templates/lab4_form.html
{% load static %} {% include "navbar.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'form.css' %}" />
    <title>Note's Form</title>
  </head>
  <body>
    <div class="formWrapper">
      <h1>Hello, Peeps!</h1>
      <form action="" method="POST">
        {% csrf_token %}
        <div class="userForm form1">
          <label for="to">To</label><br />
          <input type="text" id="to" name="to" required/><br />
        </div>
        <div class="userForm form1">
          <label for="froms">From</label><br />
          <input type="text" id="from" name="froms" required/><br />
        </div>
        <div class="userForm form2">
          <label for="title">Title</label><br />
          <input type="text" id="title" name="title" required/><br />
        </div>
        <div class="userForm">
          <label for="message">Messages</label><br />
          <textarea type="text" id="message" name="message"></textarea required><br />
        </div>
        <input class="button" type="submit" value="submit" />
      </form>
    </div>
  </body>
</html>

lab4/templates/lab4_index.html
{% load static %} {% include "navbar.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'note_table.css' %}" />
    <title>Note's</title>
  </head>
  <body>
    <div class="wrapper">
      <h1>From Who to Whom?</h1>
      <table>
        <tr>
          <th>To</th>
          <th>From</th>
          <th>Title</th>
          <th>Messages</th>
        </tr>
        {% for note in notes %}
        <tr>
          <td>{{ note.to }}</td>
          <td>{{ note.froms }}</td>
          <td>{{ note.title }}</td>
          <td>{{ note.message }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </body>
</html>

lab4/templates/lab4_note_list.html
{% load static %} {% include "navbar.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'note_list.css' %}" />
    <title>Friend's Notes</title>
  </head>
  <body>
    <div class="wrapper">
      <h1>From Who to Whom?</h1>
      <div class="CardCollection">
        {% for note in notes %}
        <div class="card">
          <p class="title">{{note.title}}</p>
          <p class="orangny"><span>From: </span> {{note.froms}}</p>
          <p class="orangny"><span>To: </span> {{note.to}}</p>
          <p class="msg">{{note.message}}</p>
        </div>
        {% endfor %}
      </div>
    </div>
  </body>
</html>

lab4/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'navbar.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark"
      style="background-color: #f2c182"
    >
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'lab4:index' %}">🗒NoTeS🗒</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'lab4:index' %}"
                >Table View</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link active" href="{% url 'lab4:noteCard' %}"
                >Card View</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'lab4:formNote' %}"
                >Add Notes
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </body>
</html>

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      {% for friend in friends %}
      <tr>
        <td>{{ friend.name }}</td>
        <td>{{ friend.npm }}</td>
        <td>{{ friend.dob }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500;700&display=swap"
      rel="stylesheet"
    />
    <style>
      body {
        font-family: Lora;
        font-size: 16px;
        line-height: 1.5;
        background-image: url("https://media.discordapp.net/attachments/876804452068257832/891608612793909248/iMac_-_1.png?width=1100&height=701");
      }

      ::-webkit-scrollbar {
        width: 5px;
      }

      ::-webkit-scrollbar-track {
        background-color: #fae5cb;
        border-radius: 100px;
      }

      ::-webkit-scrollbar-thumb {
        background-color: #c98429;
        border-radius: 2px;
      }
      .wrapper {
        margin: 80px 80px;
      }

      .CardCollection {
        margin-top: 80px;
        /* border: 1px solid red; */
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        column-gap: 20px;
        row-gap: 30px;
        justify-content: center;
      }

      .card {
        width: 300px;
        height: 300px;
        box-shadow: inset 3px 4px 4px rgba(0, 0, 0, 0.25);
        background-color: #f2c182;
        border-radius: 10px;
        padding: 20px;
        overflow-y: auto;
      }

      h1 {
        text-align: center;
        font-weight: bold;
        font-size: 48px;
        color: #7c5a36;
        text-shadow: 0px 4px 4px #c98429;
      }

      .title {
        font-weight: bold;
        font-size: 20px;
        text-align: center;
      }
      span {
        font-weight: bold;
        font-size: 16px;
      }
      .orangny {
        font-size: 16px;
        margin: 0;
        padding: 0;
      }

      .msg {
        margin-top: 16px;
      }

      @media only screen and (max-width: 912px) {
        .wrapper {
          margin: 80px 30px;
        }
      }
    </style>
    <title>Friend's Notes</title>
  </head>
  <body>
    <div class="wrapper">
      <h1>From Who to Whom?</h1>
      <div class="CardCollection">
        {% for note in notes %}
        <div class="card">
          <p class="title">{{note.title}}</p>
          <p class="orangny"><span>From: </span> {{note.froms}}</p>
          <p class="orangny"><span>To: </span> {{note.to}}</p>
          <p class="msg">{{note.message}}</p>
        </div>
        {% endfor %}
      </div>
    </div>
  </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add Friend</title>
    <style>
      form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        margin: 30px 500px;
        gap: 5px;
      }
    </style>
  </head>

  <body>
    <h1 style="text-align: center">Add Friend Form</h1>
    <form action="" method="POST">
      {% csrf_token %} {{form}}
      <input
        type="submit"
        value="submit"
        style="margin-top: 20px; width: 100px; align-self: center"
      />
    </form>
  </body>
</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
    <style>
      table,
      td,
      th {
        border: 1px solid black;
        border-collapse: collapse;
      }
    </style>
  </head>
  <body
    style="
      display: flex;
      flex-direction: column;
      justify-content: center;
      margin: 0 300px;
    "
  >
    <h1 style="text-align: center">Friend List</h1>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      {% for friend in friends %}
      <tr>
        <td>{{ friend.name }}</td>
        <td>{{ friend.npm }}</td>
        <td>{{ friend.dob }}</td>
      </tr>
      {% endfor %}
    </table>
    <a href="add" style="align-self: center; margin-top: 30px"
      ><button>Add Friend</button></a
    >
  </body>
</html>